---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Aniruddha Gokhale
# Created: Fall 2017
# Modified: Fall 2020
#
# This playbook is our demo master file
# The goal is to show how to have a single master file which then
# includes multiple plays according to some well-designed choreography
#
# This file is similar to the one in the AnsibleOnly_Local_and_Cloud folder
# For now I just kept one play in here but feel free to add more.
#####################################################
### Play 1: Get facts from all our VMs
#
# Here I show the use of import_tasks from child playbooks
#####################################################

# - name: "Create cloud vms"
#   import_playbook: tasks/create_cloud_vms.yml

#- name: "Install docker"
#  import_playbook: tasks/install_docker.yml

#- name: "Enable ufw ports"
#  import_playbook: tasks/enable_ufw_ports.yml

# - name: "Start cluster"
#   import_playbook: tasks/start_kubernetes_cluster.yml

# - name: "Taint master and compile docker files"
#   import_playbook: tasks/taint_master_compile_dockerfiles.yml

- name: "Join cluster from VM3"
  import_playbook: tasks/join_cluster_vm3.yml

- name: "Copy kubernetes deployment and service files"
  import_playbook: tasks/copy_kubernetes_deployment_files.yml

- name: "Start deployments and services"
  import_playbook: tasks/start_deployments_services.yml

# - name: "Stop deployments and services"
#   import_playbook: tasks/stop_deployments_services.yml

# - name: "Download Kafka"
#   import_playbook: tasks/download_kafka.yml
#
# - name: "Download Required Libraries"
#   import_playbook: tasks/download_java_python_kafka.yml
#
# - name: "Copy config files and consumer code to vm2"
#   import_playbook: tasks/copy_config_files_consumer_vm2.yml
#
# - name: "Copy kafka config file to vm3"
#   import_playbook: tasks/copy_config_files_vm3.yml
#
#
# - name: "Start zookeeper on vm2"
#   import_playbook: tasks/start_zookeeper.yml
#
# - name: "Start kafka broker on both VMs"
#   import_playbook: tasks/start_kafka_both_cloud.yml
#
# - name: "Download and start couchdb"
#   import_playbook: tasks/install_couchdb.yml
#
# - name: "Start producer code"
#   import_playbook: tasks/run_producer.yml
#
# - name: "Start consumer code on vm2"
#   import_playbook: tasks/start_consumer.yml
#
# - name: "Delete cloud vms"
#   import_playbook: tasks/delete_cloud_vms.yml

...
