---

- hosts: VM2
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:
  - name: Copy server.properties
    ansible.builtin.copy:
      src: ~/.ansible/server2.properties
      dest: /opt/Kafka/kafka_2.13-2.7.0/config/server.properties

  - name: Copy zookeeper.properties
    ansible.builtin.copy:
      src: ~/.ansible/zookeeper.properties
      dest: /opt/Kafka/kafka_2.13-2.7.0/config/zookeeper.properties

  - name: Copy consumer.py
    ansible.builtin.copy:
      src: ~/.ansible/consumer.py
      dest: ~/consumer.py

...
