---

- name: Create a cloud vm
  hosts: MyLocalVMs
  tasks:
    - name: launch vm2 instance
      openstack.cloud.server:
        name: team5_vm_2
        state: present
        auth:
          auth_url: https://kvm.tacc.chameleoncloud.org:5000
          application_credential_id: "f98421a8ed784a07a3a017f7403334ed"
          application_credential_secret: "ZSDcHT0lJ9gC7ciEccKCOfGz8jJXuMrnBCNLWDkr4hN3Dpxoj9yJNU_JC8v40IEbZCZc4a6KbEoBNgg13ipLWA"

        availability_zone: nova
        image: CC-Ubuntu20.04
        key_name: gebremks_chameleon
        flavor: m1.small
        security_groups:
          - default
          - ENABLE_SSH
          - ENABLE_KAFKA_COUCHDB
          - ENABLE_FECBENCH
          - ENABLE_COUCHDB_PORT
          - ENABLE_HTTP_HTTPS
        nics:
          - net-id: 4b484898-92b4-4a4b-9c5d-7d55bd72f1ee
        floating_ips:
          - 129.114.27.15	  

	  
    - name: launch vm3 instance
      openstack.cloud.server:
        name: team5_vm_3
        state: present
        auth:
          auth_url: https://kvm.tacc.chameleoncloud.org:5000
          application_credential_id: "f98421a8ed784a07a3a017f7403334ed"
          application_credential_secret: "ZSDcHT0lJ9gC7ciEccKCOfGz8jJXuMrnBCNLWDkr4hN3Dpxoj9yJNU_JC8v40IEbZCZc4a6KbEoBNgg13ipLWA"

        availability_zone: nova
        image: CC-Ubuntu20.04
        key_name: gebremks_chameleon
        flavor: m1.small
        security_groups:
          - default
          - ENABLE_SSH
          - ENABLE_KAFKA_COUCHDB
          - ENABLE_FECBENCH
          - ENABLE_COUCHDB_PORT
          - ENABLE_HTTP_HTTPS
        nics:
          - net-id: 4b484898-92b4-4a4b-9c5d-7d55bd72f1ee
        floating_ips:
          - 129.114.25.202
...
