---

- hosts: MyChameleonVMs
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:

  - name: Update Repos
    command: sudo apt update

  - name: Download java
    command: sudo apt install default-jre -y
    register: output

  - name: Download pip3
    command: sudo apt install python3-pip -y

  - name: Print the output
    debug:
      msg: "{{ output }}"
...
