---

- hosts: MyChameleonVMs
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:

  - name: Allow port 9092
    command: sudo ufw allow 9092

  - name: Allow port 2181
    command: sudo ufw allow 2181

  - name: Allow port 5984
    command: sudo ufw allow 5984

  - name: Allow port 2379:2380/tcp
    command: sudo ufw allow 2379:2380/tcp

  - name: Allow port 6443/tcp
    command: sudo ufw allow 6443/tcp

  - name: Allow port 10250:10252/tcp
    command: sudo ufw 10250:10252/tcp

  - name: Allow port 8285/udp
    command: sudo ufw allow 8285/udp

  - name: Allow port 8472/udp
    command: sudo ufw allow 8472/udp

  - name: Allow port 5000/tcp
    command: sudo ufw allow 5000/tcp

  - name: Allow port 30000:30004/tcp
    command: sudo ufw allow 30000:30004/tcp

  - name: Allow port 30005/tcp
    command: sudo ufw allow 30005/tcp

  - name: Allow port 30006
    command: sudo ufw allow 30006/tcp
