---

- hosts: MyChameleonVMs
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:
  # - name: Enable Ufw
  #   command: sudo ufw enable

  - name: Allow port 9092
    command: sudo ufw allow 9092

  - name: Allow port 2181
    command: sudo ufw allow 2181

  - name: Allow port 5984
    command: sudo ufw allow 5984



...
