---

- hosts: VM2
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:

  - name: Start kubeadm cluster
    command: sudo kubeadm init --node-name kubemaster -pod-network-cidr=10.244.0.0/16

  - name: Copy shell file
    copy: src=~/.ansible/docker_kubernetes_commands.sh dest=/opt/docker_kubernetes_commands.sh
    become: true

  - name: Run non-interactive shell command to start cluster and tainting
    command: sh /opt/docker_kubernetes_commands.sh
    become: true
    register: output

  - name: Download couchdb
    command: pip3 install couchdb

  - name: Run consumer.py
    command: python3 /opt/consumer.py
    async: 120
    poll: 0
    register: output

  - name: Print the output
    debug:
      msg: "{{ output }}"


...
