---

- hosts: MyChameleonVMs
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:
  - name: Start kafka brokers
    command: chdir=/opt/Kafka/kafka_2.13-2.7.0 sudo bin/kafka-server-start.sh config/server.properties
    async: 60
    poll: 0
    register: output

  - name: Print the output
    debug:
      msg: "{{ output }}"
  # - name: Check if successful
  #   async_status: jid="{{ output.ansible_job_id }}"
  #   register: result
  #   failed_when: result.finished != 1 or "Finished 'command'" not in result.stdout


...
