kubectl delete -f kafka_broker1_service.yaml
kubectl delete -f kafka_broker1_deployment.yaml
kubectl delete -f kafka_broker0_service.yaml
kubectl delete -f kafka_broker0_deployment.yaml
kubectl delete -f zookeeper_service.yaml
kubectl delete -f zookeeper_deployment.yaml
kubectl delete -f couchdb_service.yaml
kubectl delete -f couchdb_deployment.yaml
kubectl delete -f consumer_deployment.yaml
