kubectl delete -f /home/cc/kafka_broker1_service.yaml
kubectl delete -f /home/cc/kafka_broker1_deployment.yaml
kubectl delete -f /home/cc/kafka_broker0_service.yaml
kubectl delete -f /home/cc/kafka_broker0_deployment.yaml
kubectl delete -f /home/cc/zookeeper_service.yaml
kubectl delete -f /home/cc/zookeeper_deployment.yaml
kubectl delete -f /home/cc/couchdb_service.yaml
kubectl delete -f /home/cc/couchdb_deployment.yaml
kubectl delete -f /home/cc/consumer_deployment.yaml
